### ISSUE TITLE
Highlight global variables

### ISSUE THREAD

**Issue by NiedziolkaMichal** [lezer-parser/javascript#10]
There are 4 [global properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#value_properties) in JavaScript: `undefined`, `NaN`, `Infinity` & `globalThis`. All of those are unique in the language, they have special features and undefined is also a primitive value. Current [highlight.js](https://github.com/lezer-parser/javascript/blob/main/src/highlight.js) treats them as `variableName`, because of which they share color with any other variable. Would it be possible to put those 4 values under a unique tag, so they can have a different style than rest of the variables? Two of those: `undefined` & `NaN` could easily share tag with `null`.

**Comment by marijnh** [comment]
Not really, because they can be shadowed (`function(undefined) { return undefined + 1 }`), so a parser that doesn't track scopes can't really distinguish them from regular variable names. As such, I've decided to not parse them specially.

**Comment by josephrocca** [comment]
Am I correct in understanding that this means we need to use the legacy JavaScript parser if we want to color `foo` and `bar` differently on the `return foo + bar` line in below example?
```js
window.bar = 10;

function fn() {
  let foo = 10;
  return foo + bar; // can't color these differently with @lezer-parser/javascript?
}
```

---

*(Sorry for bumping old thread - I found this issue while searching the question, so I assume others will hit this thread too, hence probably better to compile info here rather than starting a new issue.)*

**Comment by marijnh** [comment]
Correct. The Lezer grammar doesn't track scopes.
